### ISSUE TITLE
Ollama doesnt use GPU, resulting in very slow executionss

### ISSUE THREAD

**Issue by beetrandahiya** [browser-use/web-ui#324]
I setup web-ui today, and its not using GPU.
I've got Ollama and Open webui set up very well and they work like butter.

Already tried:
1. changed utils.py to add num_gpu=1, num_threads=0. Restarted the web UI, no change

Has anybody got it working with ollama on GPU? any help will be appreciated.

**Comment by cheesesilk** [comment]
Same here.  Running Ollama in Ubuntu is just fine utilizing GPU, but when I launch Browser Use, it doesn't use my GPU.  Need help too.

**Comment by warmshao** [comment]
> I setup web-ui today, and its not using GPU. I've got Ollama and Open webui set up very well and they work like butter.
> 
> Already tried:
> 
> 1. changed utils.py to add num_gpu=1, num_threads=0. Restarted the web UI, no change
> 
> Has anybody got it working with ollama on GPU? any help will be appreciated.

Try to reduce num_ctx? Not sure whether is a chatollama problem, I cannot replicate it on my 4090

**Comment by ten80** [comment]
Same problem for me, first i thought it would not work, because nothing happend, but its because my GPU does nearly nothing and my CPU is doing the "most".

**Comment by davehardy20** [comment]
I have the same problem, docker ollama, native ollama no worky only CPU. I have a 3090

**Comment by cheesesilk** [comment]
So today mine was working with an 8B model for some reason. Usually can run 14B well. Maybe need to use a smaller model? or just relaunch and try a few times.

**Comment by nico721GD** [comment]
just updated my ollama version to the latest, worked for me

**Comment by davehardy20** [comment]
@davehardy20 I use the Dockge tool to manage my docker compose and containers etc, I moved the webui folder into the /opt/stack folder, (this is where the tool manages containers etc). After running the webui container here I could use the ollama container with GPU pass through. Although I had another issue in that the browser never opened nor did the headless version work.

**Comment by menders** [comment]
Same issue here. Open-webui docker works fine with my local ollama install using GPU, but the web-ui docker container is using my CPU. Went a step further and tested my ollama API using curl and confirmed that was using the GPU as well.
